development:
  api_key:     'demo_key'
  api_secret:  't3sts3cr3t'
  endpoint:    'http://api.dev.flexmls.com'

alpha:
  api_key:     'alpha_demo_key'
  api_secret:  'alpha_t3sts3cr3t'
  endpoint:    'http://api.alpha.flexmls.com'

production:
  api_key:     'prod_demo_key'
  api_secret:  'prod_t3sts3cr3t'
  endpoint:    'http://api.test.flexmls.com'

